In [13]:
from numpy import *
#array()
arr = array([24,34,33,1,2,334,4,5,5,3,2.0])
print(arr)
print(arr.dtype)

[ 24.  34.  33.   1.   2. 334.   4.   5.   5.   3.   2.]
float64


In [6]:
arr1 = linspace(0,10,5)
#linspace()
print(arr1)
print(arr1.dtype)

[ 0.   2.5  5.   7.5 10. ]
float64


In [8]:
arr2 = arange(1,20,5)
#arange() left 5
print(arr2)
print(arr2.dtype)


[ 1  6 11 16]
int64


In [10]:
arr3 = logspace(0,10,5)
#logspace
print(arr3)
print(arr3.dtype)

[1.00000000e+00 3.16227766e+02 1.00000000e+05 3.16227766e+07
 1.00000000e+10]
float64


In [12]:
arr4 = zeros(5,int)
#zeros()
print(arr4)

[0 0 0 0 0]


In [13]:
arr5 = ones(5,int)
#ones()
print(arr5)

[1 1 1 1 1]


In [23]:
arr6 = [5,1,9]
#1 normal copy
arr7=arr6
print(arr7)
print(arr6)
#2 Shallow copy
arr8= array([12,34,45])
arr9 = arr8.view()
arr8[1]=8
print(arr8)
print(arr9)
#2 deep copy
arr10= array([1,34,45])
arr11 = arr10.copy()
arr10[1]=8
print(arr10)
print(arr11)

[5, 1, 9]
[5, 1, 9]
[12  8 45]
[12  8 45]
[ 1  8 45]
[ 1 34 45]


In [6]:
arr01 = array([1, 4, 2, 5, 3])
print(arr01)

[1 4 2 5 3]


In [8]:
arr02 = array([3.14, 4, 2, 3])
print(arr02)


[3.14 4.   2.   3.  ]


In [16]:
# nested lists result in multidimensional arrays
arr03 = array([range(i, i + 3) for i in [2, 4, 6]])
print(arr03)

[[2 3 4]
 [4 5 6]
 [6 7 8]]


In [17]:
import numpy
# Create a length-10 integer array filled with zeros
numpy.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
# Create a 3x5 floating-point array filled with 1s
numpy.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
#Create a 3x5 array filled with 3.14
numpy.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [20]:
 # Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
numpy.random.normal(0, 1, (3, 3))

array([[ 0.23468374,  1.72316413, -1.26255883],
       [-0.04721789,  1.10499173, -0.44890853],
       [-0.01860151, -0.50190415, -0.22180784]])

In [4]:
import numpy as np
np.random.seed(0)  # seed for reproducibility
x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional
print(x1)
print(x2)
print(x3)
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

[5 0 3 3 7 9]
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]
x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
itemsize: 8 bytes
nbytes: 480 bytes


In [7]:
x1


array([5, 0, 3, 3, 7, 9])

In [8]:
x1[-1]

9

In [9]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [11]:
x2[0, 0]

3

In [12]:
x2[2, 0]

1

In [13]:
x2[2, -1]

7

In [15]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
x[:5]  # first five elements

array([0, 1, 2, 3, 4])

In [18]:
x[4:7]  # middle subarray

array([4, 5, 6])

In [19]:
x[1::2]  # every other element, starting at index 1

array([1, 3, 5, 7, 9])

In [20]:
x[::-1]  # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [21]:
x[5::-2]  # reversed every other from index 5

array([5, 3, 1])

In [23]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [24]:
x2[:2, :3]  # two rows, three columns

array([[3, 5, 2],
       [7, 6, 8]])

In [25]:
x2[:3, ::2]  # all rows, every other column

array([[3, 2],
       [7, 8],
       [1, 7]])

In [26]:
x2[::-1, ::-1]

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

In [27]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[3 5]
 [7 6]]


In [28]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [29]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [30]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [31]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [32]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [33]:
#Reshaping of Arrays
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [34]:
x = np.array([1, 2, 3])

# row vector via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [35]:
# row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [36]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [37]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [38]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [41]:
grid = np.array([[1, 2, 3],
[4, 5, 6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
 # concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [43]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                         [6, 5, 4]])
# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [44]:
# horizontally stack the arrays
y = np.array([[99],
[99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [45]:
#Splitting of arrays
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [46]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [47]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [48]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [49]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [50]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

1.94 s ± 404 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [51]:
x = np.arange(9).reshape((3, 3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

In [52]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # floor division

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [53]:
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


In [54]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [55]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [56]:
np.abs(x)

array([2, 1, 0, 1, 2])

In [57]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

In [58]:
theta = np.linspace(0, np.pi, 3)

In [59]:
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [60]:
x = [-1, 0, 1]
print("x         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x         =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


In [61]:
#Exponents and logarithms
x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

x     = [1, 2, 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [ 3  9 27]


In [62]:
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [63]:
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]


In [66]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[ 0. 10. 20. 30. 40.]


In [67]:
L = np.random.random(100)
sum(L)

50.461758453195614

In [68]:
M = np.random.random((3, 4))
print(M)

[[0.49555108 0.9552979  0.81778172 0.49902653]
 [0.22465879 0.89005733 0.30654364 0.37441302]
 [0.75259926 0.17746194 0.10144419 0.9999925 ]]


In [69]:
M.min(axis=0)

array([0.22465879, 0.17746194, 0.10144419, 0.37441302])

In [70]:
M.max(axis=1)

array([0.9552979 , 0.89005733, 0.9999925 ])

In [71]:
# Broadcasting
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b

array([5, 6, 7])

In [72]:
a + 5

array([5, 6, 7])

In [73]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]
print(a)
print(b)

[0 1 2]
[[0]
 [1]
 [2]]


In [74]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])